export const projects = [
  {
    id: "1",
    name: "Crm for education centers",
    image: "./crm.png",
    url: "https://crmsystemuz.netlify.app/",
    gitHubUrl: "https://github.com/javohirbackendDeveloper/crm_backend",
    order: 1,
  },
  {
    id: "2",
    name: "It market website",
    image: "./it_market.png",
    url: "",
    gitHubUrl: "https://github.com/javohirbackendDeveloper/it_market_backend",
    order: 2,
  },
  {
    id: "3",
    name: "Markethub website",
    image: "./olx.png",
    url: "",
    gitHubUrl: "https://github.com/javohirbackendDeveloper/olx_clone_backend",
    order: 3,
  },
  {
    id: "4",
    name: "E-Commerce platform",
    image: "./eCommerce.png",
    url: "",
    gitHubUrl: "https://github.com/javohirbackendDeveloper/wear_e_commerce",
    order: 4,
  },
  {
    id: "5",
    name: "Realtime chat application",
    image: "./chat.png",
    gitHubUrl: "https://github.com/javohirbackendDeveloper/chatApp",
    url: "",
    order: 5,
  },
  {
    id: "6",
    name: "Quiz app",
    image: "./quiz.png",
    gitHubUrl: "https://github.com/javohirbackendDeveloper/Quiz_app",
    url: "",
    order: 6,
  },
];
