export const projects = [
  {
    id: "1",
    name: "Crm for education centers",
    image: "./crm.png",
    url: "https://crmsystemuz.netlify.app/",
    gitHubUrl: "https://github.com/javohirbackendDeveloper/crm_backend",
    order: 1,
  },
  {
    id: "8",
    name: "TezBuy e-commerce admin panel",
    image: "./tezbuyAdminPanel.png",
    url: "https://e-commerce-admin-panel-indol.vercel.app/dashboard",
    gitHubUrl:
      "https://github.com/javohirbackendDeveloper/e-commerce-admin-panel",
    order: 8,
  },
  {
    id: "10",
    name: "TezBuy e-commerce backend with microservices",
    image: "./tezbuyBackend.png",
    gitHubUrl: "https://github.com/javohirbackendDeveloper/e-commerce-backend",
    order: 10,
  },
  {
    id: "9",
    name: "Tezbuy main website",
    image: "./tezbuyMainWebsite.png",
    url: "https://tezbuy-user-panel.vercel.app/",
    gitHubUrl:
      "https://github.com/javohirbackendDeveloper/e-commerce-user-panel",
    order: 10,
  },
  {
    id: "2",
    name: "It market website",
    image: "./it_market.png",
    url: "",
    gitHubUrl: "https://github.com/javohirbackendDeveloper/it_market_backend",
    order: 2,
  },
  {
    id: "3",
    name: "Markethub website",
    image: "./olx.png",
    url: "",
    gitHubUrl: "https://github.com/javohirbackendDeveloper/olx_clone_backend",
    order: 3,
  },
  {
    id: "4",
    name: "E-Commerce platform",
    image: "./eCommerce.png",
    url: "",
    gitHubUrl: "https://github.com/javohirbackendDeveloper/wear_e_commerce",
    order: 4,
  },
  {
    id: "5",
    name: "Realtime chat application",
    image: "./chat.png",
    gitHubUrl: "https://github.com/javohirbackendDeveloper/chatApp",
    url: "",
    order: 5,
  },
  {
    id: "6",
    name: "Quiz app",
    image: "./quiz.png",
    gitHubUrl: "https://github.com/javohirbackendDeveloper/Quiz_app",
    url: "",
    order: 6,
  },
  {
    id: "7",
    name: "Online hr website",
    image: "./online_hr.png",
    gitHubUrl: "https://github.com/javohirbackendDeveloper/jobs_apply_backend",
    url: "https://jobs-apply-frontend-r71n.vercel.app/",
    order: 6,
  },
];
